CREATE TABLE users (
  id       BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(256)    NOT NULL UNIQUE,
  password VARCHAR(256)    NOT NULL,
  nickname VARCHAR(256)    NOT NULL,
  email    VARCHAR(256)    NOT NULL UNIQUE,
  enabled  BOOLEAN
)
  ENGINE = InnoDB;

CREATE TABLE authorities (
  id        BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id   BIGINT UNSIGNED NOT NULL,
  authority VARCHAR(256),
  FOREIGN KEY (user_id) REFERENCES users (id)
    ON DELETE CASCADE
)
  ENGINE = InnoDB;

CREATE TABLE SPRING_SESSION (
  PRIMARY_ID            CHAR(36) NOT NULL,
  SESSION_ID            CHAR(36) NOT NULL,
  CREATION_TIME         BIGINT   NOT NULL,
  LAST_ACCESS_TIME      BIGINT   NOT NULL,
  MAX_INACTIVE_INTERVAL INT      NOT NULL,
  EXPIRY_TIME           BIGINT   NOT NULL,
  PRINCIPAL_NAME        VARCHAR(100),
  CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
)
  ENGINE = InnoDB;

CREATE UNIQUE INDEX SPRING_SESSION_IX1
  ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2
  ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3
  ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
  SESSION_PRIMARY_ID CHAR(36)     NOT NULL,
  ATTRIBUTE_NAME     VARCHAR(200) NOT NULL,
  ATTRIBUTE_BYTES    BLOB         NOT NULL,
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION (PRIMARY_ID)
    ON DELETE CASCADE
)
  ENGINE = InnoDB;

CREATE INDEX SPRING_SESSION_ATTRIBUTES_IX1
  ON SPRING_SESSION_ATTRIBUTES (SESSION_PRIMARY_ID);
