spring:
  datasource:
    url: jdbc:mysql://localhost:63306/webauthn?useSSL=false
    username: root
    password: sa
    driverClassName: com.mysql.jdbc.Driver
  session:
    store-type: jdbc
  jpa:
    show-sql: true
    open-in-view: true
